import {sessionResponse} from '../lib/session';
import {createDiscovery} from '../lib/discovery';
import React from 'react';
import {renderToReadableStream} from 'react-dom/server.edge';
import {Surface} from './surface';
import {companies} from '../lib/companies';
import {GET as calendar} from '../app/api/calendar/[id]/route';
import client from './generated/client.txt';
import css from './generated/style.txt';
const headers={'X-Content-Type-Options':'nosniff','Referrer-Policy':'strict-origin-when-cross-origin','Permissions-Policy':'camera=(), microphone=(), geolocation=()','X-Robots-Tag':'noindex, nofollow'};
const esc=(s:string)=>s.replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
export default {async fetch(request:Request){const url=new URL(request.url);if(request.method!=='GET'&&request.method!=='HEAD')return new Response('Method not allowed',{status:405,headers:{...headers,Allow:'GET, HEAD'}});const path=url.pathname; if(path==='/api/session'){const response=sessionResponse(request.headers);return request.method==='HEAD'?new Response(null,{headers:response.headers}):response;} if(path==='/app.js')return new Response(client,{headers:{...headers,'Content-Type':'text/javascript; charset=utf-8'}});if(path==='/style.css')return new Response(css,{headers:{...headers,'Content-Type':'text/css; charset=utf-8'}});if(path==='/robots.txt')return new Response('User-agent: *\nDisallow: /\n',{headers:{...headers,'Content-Type':'text/plain'}});if(path.startsWith('/api/calendar/'))return calendar(request,{params:Promise.resolve({id:path.slice('/api/calendar/'.length)})});const c=companies.find(c=>path==='/companies/'+c.id);const known=path==='/'||path==='/anniversaries'||!!c;const title=c?c.name+' | 기업의 날':path==='/anniversaries'?'창립기념일 | 기업의 날':'기업의 날 — 기업을 찾고, 중요한 날을 기억하세요';const discovery=path==='/'?createDiscovery():{};const stream=await renderToReadableStream(<Surface path={path} discovery={discovery}/>);const body=await new Response(stream).text();const html=`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${esc(title)}</title><meta name="description" content="${esc(c?.summary??'국내 기업 정보와 창립기념일을 검색하고 캘린더에 추가하세요. 초기 등록 기업부터 시작합니다.')}"><meta name="robots" content="noindex,nofollow"><link rel="stylesheet" href="/style.css"></head><body><div id="root" data-discovery="${esc(JSON.stringify(discovery))}">${body}</div><script type="module" src="/app.js"></script></body></html>`;return new Response(request.method==='HEAD'?null:html,{status:known?200:404,headers:{...headers,'Content-Type':'text/html; charset=utf-8','Cache-Control':'no-store','Content-Security-Policy':"default-src 'self'; script-src 'self'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; object-src 'none'; base-uri 'none'"}})}};

